plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()

}

dependencies {
    implementation "org.apache.commons:commons-lang3:${commons}"
    implementation "com.google.guava:guava:${guava}"
    testImplementation "org.junit.jupiter:junit-jupiter-api:${junit}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${junit}"
}

test {
    useJUnitPlatform()
}